### ISSUE TITLE
Is it possible to support hevc flv?

### ISSUE THREAD

**Issue by iwestlin** [eko5624/mpv-mac#1]
by applying this patch: https://github.com/runner365/ffmpeg_rtmp_h265

**Comment by eko5624** [comment]
有hevc flv的样片吗，我好去下载测试。
还有就是不知道你提到这个仓库里的文件是否使用于最新的ffmpeg

**Comment by iwestlin** [comment]
有的：https://github.com/delhi2050/flv-hevc-test-video

[runner365/ffmpeg_rtmp_h265](https://github.com/runner365/ffmpeg_rtmp_h265) 这个仓库的分支名应该就对应ffmpeg的版本号，最新支持到6.0

**Comment by eko5624** [comment]
现在ffmpeg最新版都到7.1了，那不就是不支持最新的ffmpeg嘛。

**Comment by iwestlin** [comment]
恐怕是的😢，关注这个issue https://github.com/runner365/ffmpeg_rtmp_h265/issues/11

**Comment by eko5624** [comment]
那算了，等上游仓库ffmpeg_rtmp_h265更新吧。

**Comment by iwestlin** [comment]
我又找到个patch https://github.com/yt-dlp/FFmpeg-Builds/blob/master/patches/ffmpeg/master/0001-Nonstandard-HEVC-over-FLV.patch

我刚下载了下它提供的7.1版本的linux二进制ffmpeg，是支持hevc的flv的

**Comment by eko5624** [comment]
好的，我去打这个补丁试试看。

**Comment by eko5624** [comment]
Done!
https://github.com/eko5624/mpv-mac/releases/tag/2024-11-18

**Comment by iwestlin** [comment]
好耶🥳
